'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")>  _
Partial Friend NotInheritable Class Protocols
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Protocols = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Protocols()),Protocols)
    
    Public Shared ReadOnly Property [Default]() As Protocols
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ProxyAddress() As String
        Get
            Return CType(Me("ProxyAddress"),String)
        End Get
        Set
            Me("ProxyAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ProxyUserName() As String
        Get
            Return CType(Me("ProxyUserName"),String)
        End Get
        Set
            Me("ProxyUserName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ProxyPassword() As String
        Get
            Return CType(Me("ProxyPassword"),String)
        End Get
        Set
            Me("ProxyPassword") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ProxyDomain() As String
        Get
            Return CType(Me("ProxyDomain"),String)
        End Get
        Set
            Me("ProxyDomain") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UseProxy() As Boolean
        Get
            Return CType(Me("UseProxy"),Boolean)
        End Get
        Set
            Me("UseProxy") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ProxyByPassOnLocal() As Boolean
        Get
            Return CType(Me("ProxyByPassOnLocal"),Boolean)
        End Get
        Set
            Me("ProxyByPassOnLocal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
    Public Property ProxyPort() As Integer
        Get
            Return CType(Me("ProxyPort"),Integer)
        End Get
        Set
            Me("ProxyPort") = value
        End Set
    End Property
End Class
