'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")>  _
Partial Friend NotInheritable Class IndirmeAyar
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As IndirmeAyar = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New IndirmeAyar()),IndirmeAyar)
    
    Public Shared ReadOnly Property [Default]() As IndirmeAyar
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
    Public Property RetryDelay() As Integer
        Get
            Return CType(Me("RetryDelay"),Integer)
        End Get
        Set
            Me("RetryDelay") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
    Public Property MaxRetries() As Integer
        Get
            Return CType(Me("MaxRetries"),Integer)
        End Get
        Set
            Me("MaxRetries") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DownloadFolder() As String
        Get
            Return CType(Me("DownloadFolder"),String)
        End Get
        Set
            Me("DownloadFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("32")>  _
    Public Property EnFazlaAyniAndaIndirilecekSegmentSayisi() As Integer
        Get
            Return CType(Me("EnFazlaAyniAndaIndirilecekSegmentSayisi"),Integer)
        End Get
        Set
            Me("EnFazlaAyniAndaIndirilecekSegmentSayisi") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property kod() As String
        Get
            Return CType(Me("kod"),String)
        End Get
        Set
            Me("kod") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property kadi() As String
        Get
            Return CType(Me("kadi"),String)
        End Get
        Set
            Me("kadi") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property sifre() As String
        Get
            Return CType(Me("sifre"),String)
        End Get
        Set
            Me("sifre") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property sunucu() As String
        Get
            Return CType(Me("sunucu"),String)
        End Get
        Set
            Me("sunucu") = value
        End Set
    End Property
End Class
