'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")>  _
Partial Friend NotInheritable Class Kontrol
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Kontrol = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Kontrol()),Kontrol)
    
    Public Shared ReadOnly Property [Default]() As Kontrol
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ViewTransDetails() As Boolean
        Get
            Return CType(Me("ViewTransDetails"),Boolean)
        End Get
        Set
            Me("ViewTransDetails") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ViewToolbar() As Boolean
        Get
            Return CType(Me("ViewToolbar"),Boolean)
        End Get
        Set
            Me("ViewToolbar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ViewGrid() As Boolean
        Get
            Return CType(Me("ViewGrid"),Boolean)
        End Get
        Set
            Me("ViewGrid") = value
        End Set
    End Property
End Class
